<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>SpaceInvaders</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpaceInvaders.Core\SpaceInvaders.Core.csproj" />
  </ItemGroup>
</Project>